### ISSUE TITLE
Feature Request: Show Unresolved/Resolved Thread

### ISSUE THREAD

**Issue by TamasRusvai** [BCsabaEngine/gitlab-mr-monitor#5]
Hello,

This is a great tool. 💯 

I would like to request a feature. It would be great help to show the resolved/unresolved threads in the list as well.

Like in this gitlab Feature Request: https://gitlab.com/gitlab-org/gitlab/-/issues/196807

**Comment by BCsabaEngine** [comment]
Normally, gitlab tags MRs with a Discussion flag when a discussion has started. We also indicate this.
We also display the number of comments in the next version (1.3.5?)

Note that the pipeline can also perform commenting activities, these will also appear as comments!

ps: Unfortunately, we cannot separate comments from threads (by API)

**Comment by BCsabaEngine** [comment]
v1.3.5 released, deployed. Please refresh in browser or restart installed application.
