### ISSUE TITLE
[Feature Req] Show approves in MR card

### ISSUE THREAD

**Issue by gergely-sallai** [BCsabaEngine/gitlab-mr-monitor#6]
I'd be a nice addition to show approves for a specific MR.

Either by:
- Showing how many approves it has
- or by showing who has approved from the assignees

Whichever is feasible or easier.

**Comment by BCsabaEngine** [comment]
Unfortunately, the gitlab API does not support the number and availability of approves. We did not find the source of the data at the highest level (level of MRs), which is not directly available, in sub-queries too (going through all MRs). Sorry!
